cmd: "gradle"
name: "gradle build"
args:
  - "build"
env:
  DEFAULT_JVM_OPTS: "--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED"
atomCommandName: "atom-custom:gradlebuild"
